#!/usr/bin/env bash
set -euo pipefail

TARGET="both"
TOOLKIT_DIR=""
CODEX_SKILLS_DIR=""
CLAUDE_SKILLS_DIR=""
REPO_URL="https://github.com/Malac12/silmaril-CDP-tools.git"
ARCHIVE_URL="https://github.com/Malac12/silmaril-CDP-tools/archive/refs/heads/main.zip"
FORCE=0
SKIP_SMOKE_TEST=0
DRY_RUN=0

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

write_step() {
  printf '==> %s\n' "$1"
}

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

canonical_dir() {
  (
    cd "$1"
    pwd -P
  )
}

usage() {
  cat <<'EOF'
Install the silmaril-cdp skill for Codex and/or Claude Code on macOS.

Usage:
  ./install-skill.sh [options]

Options:
  --target, -Target <codex|claude|both>
  --toolkit-dir, -ToolkitDir <path>
  --codex-skills-dir, -CodexSkillsDir <path>
  --claude-skills-dir, -ClaudeSkillsDir <path>
  --repo-url, -RepoUrl <url>
  --archive-url, -ArchiveUrl <url>
  --force, -Force
  --skip-smoke-test, -SkipSmokeTest
  --dry-run, -DryRun
  --help, -Help
EOF
}

test_repo_root() {
  local path="${1:-}"
  [[ -n "$path" ]] &&
    [[ -f "$path/skills/silmaril-cdp/SKILL.md" ]] &&
    [[ -f "$path/silmaril-mac.sh" ]]
}

default_toolkit_dir() {
  printf '%s\n' "$HOME/silmaril-cdp-tools"
}

install_toolkit_archive() {
  local destination_dir="$1"
  local download_url="$2"
  local temp_root
  local zip_path
  local extract_root
  local expanded_repo

  temp_root="$(mktemp -d "${TMPDIR:-/tmp}/silmaril-install.XXXXXX")"
  zip_path="$temp_root/toolkit.zip"
  extract_root="$temp_root/extract"

  mkdir -p "$extract_root"

  cleanup() {
    rm -rf "$temp_root"
  }
  trap cleanup RETURN

  if ! command -v curl >/dev/null 2>&1; then
    die "curl was not found on PATH, and git is unavailable. Install curl or git to continue."
  fi

  curl -fsSL "$download_url" -o "$zip_path"

  if command -v unzip >/dev/null 2>&1; then
    unzip -q "$zip_path" -d "$extract_root"
  elif command -v ditto >/dev/null 2>&1; then
    ditto -x -k "$zip_path" "$extract_root"
  else
    die "Neither unzip nor ditto is available to extract the toolkit archive."
  fi

  expanded_repo="$(find "$extract_root" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
  [[ -n "$expanded_repo" ]] || die "Downloaded archive did not contain a repository root directory."

  mv "$expanded_repo" "$destination_dir"
}

resolve_repo_root() {
  local requested_toolkit_dir="$1"
  local replace_existing="$2"
  local simulation_mode="$3"
  local download_repo_url="$4"
  local download_archive_url="$5"
  local destination_dir
  local parent_dir

  if test_repo_root "$SCRIPT_DIR"; then
    canonical_dir "$SCRIPT_DIR"
    return
  fi

  destination_dir="$requested_toolkit_dir"
  if [[ -z "$destination_dir" ]]; then
    destination_dir="$(default_toolkit_dir)"
  fi

  if test_repo_root "$destination_dir"; then
    canonical_dir "$destination_dir"
    return
  fi

  if [[ -e "$destination_dir" ]]; then
    if [[ "$replace_existing" -ne 1 ]]; then
      die "Existing path is not a Silmaril toolkit checkout: $destination_dir. Re-run with --force to replace it."
    fi

    if [[ "$simulation_mode" -eq 1 ]]; then
      write_step "Would remove existing path: $destination_dir"
    else
      rm -rf "$destination_dir"
    fi
  fi

  if [[ "$simulation_mode" -eq 1 ]]; then
    write_step "Would install toolkit repo to $destination_dir"
    printf '%s\n' "$destination_dir"
    return
  fi

  parent_dir="$(dirname "$destination_dir")"
  mkdir -p "$parent_dir"

  if command -v git >/dev/null 2>&1; then
    write_step "Cloning toolkit with git into $destination_dir"
    git clone "$download_repo_url" "$destination_dir"
  else
    write_step "git not found. Downloading toolkit archive into $destination_dir"
    install_toolkit_archive "$destination_dir" "$download_archive_url"
  fi

  if ! test_repo_root "$destination_dir"; then
    die "Installed toolkit checkout is missing required files: $destination_dir"
  fi

  chmod +x "$destination_dir/silmaril-mac.sh"
  canonical_dir "$destination_dir"
}

write_local_paths_file() {
  local skill_dir="$1"
  local toolkit_root="$2"
  local toolkit_command="$toolkit_root/silmaril-mac.sh"
  local powershell_entry="$toolkit_root/silmaril.ps1"
  local local_paths_path="$skill_dir/LOCAL_PATHS.md"

  cat >"$local_paths_path" <<EOF
# Local Paths

This file was generated by \`install-skill.sh\`.

- Toolkit root: $toolkit_root
- macOS launcher: $toolkit_command
- PowerShell entrypoint: $powershell_entry
- Repository URL: $REPO_URL
EOF
}

install_skill() {
  local source_skill_dir="$1"
  local destination_skill_dir="$2"
  local toolkit_root="$3"
  local target_name="$4"
  local simulation_mode="$5"
  local destination_parent

  if [[ "$simulation_mode" -eq 1 ]]; then
    write_step "Would install $target_name skill to $destination_skill_dir"
    return
  fi

  destination_parent="$(dirname "$destination_skill_dir")"
  mkdir -p "$destination_parent"
  rm -rf "$destination_skill_dir"

  cp -R "$source_skill_dir" "$destination_skill_dir"
  write_local_paths_file "$destination_skill_dir" "$toolkit_root"
}

assert_install_result() {
  local toolkit_root="$1"
  shift
  local toolkit_command="$toolkit_root/silmaril-mac.sh"
  local skill_dir

  [[ -f "$toolkit_command" ]] || die "Toolkit command not found after install: $toolkit_command"

  for skill_dir in "$@"; do
    [[ -f "$skill_dir/SKILL.md" ]] || die "Installed skill is missing SKILL.md: $skill_dir"
    [[ -f "$skill_dir/LOCAL_PATHS.md" ]] || die "Installed skill is missing LOCAL_PATHS.md: $skill_dir"
  done
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target|-Target)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      TARGET="$2"
      shift 2
      ;;
    --toolkit-dir|-ToolkitDir)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      TOOLKIT_DIR="$2"
      shift 2
      ;;
    --codex-skills-dir|-CodexSkillsDir)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      CODEX_SKILLS_DIR="$2"
      shift 2
      ;;
    --claude-skills-dir|-ClaudeSkillsDir)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      CLAUDE_SKILLS_DIR="$2"
      shift 2
      ;;
    --repo-url|-RepoUrl)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      REPO_URL="$2"
      shift 2
      ;;
    --archive-url|-ArchiveUrl)
      [[ $# -ge 2 ]] || die "Missing value for $1"
      ARCHIVE_URL="$2"
      shift 2
      ;;
    --force|-Force)
      FORCE=1
      shift
      ;;
    --skip-smoke-test|-SkipSmokeTest)
      SKIP_SMOKE_TEST=1
      shift
      ;;
    --dry-run|-DryRun)
      DRY_RUN=1
      shift
      ;;
    --help|-Help|-h)
      usage
      exit 0
      ;;
    *)
      die "Unknown argument: $1"
      ;;
  esac
done

case "$TARGET" in
  codex|claude|both)
    ;;
  *)
    die "Invalid target: $TARGET. Expected codex, claude, or both."
    ;;
esac

if [[ -z "$TOOLKIT_DIR" ]]; then
  TOOLKIT_DIR="$(default_toolkit_dir)"
fi
if [[ -z "$CODEX_SKILLS_DIR" ]]; then
  CODEX_SKILLS_DIR="$HOME/.codex/skills"
fi
if [[ -z "$CLAUDE_SKILLS_DIR" ]]; then
  CLAUDE_SKILLS_DIR="$HOME/.claude/skills"
fi

REPO_ROOT="$(resolve_repo_root "$TOOLKIT_DIR" "$FORCE" "$DRY_RUN" "$REPO_URL" "$ARCHIVE_URL")"
SOURCE_SKILL_DIR="$REPO_ROOT/skills/silmaril-cdp"
[[ "$DRY_RUN" -eq 1 || -d "$SOURCE_SKILL_DIR" ]] || die "Skill source directory not found: $SOURCE_SKILL_DIR"

INSTALLED_SKILL_DIRS=()

if [[ "$TARGET" == "codex" || "$TARGET" == "both" ]]; then
  CODEX_SKILL_DIR="$CODEX_SKILLS_DIR/silmaril-cdp"
  install_skill "$SOURCE_SKILL_DIR" "$CODEX_SKILL_DIR" "$REPO_ROOT" "Codex" "$DRY_RUN"
  INSTALLED_SKILL_DIRS+=("$CODEX_SKILL_DIR")
fi

if [[ "$TARGET" == "claude" || "$TARGET" == "both" ]]; then
  CLAUDE_SKILL_DIR="$CLAUDE_SKILLS_DIR/silmaril-cdp"
  install_skill "$SOURCE_SKILL_DIR" "$CLAUDE_SKILL_DIR" "$REPO_ROOT" "Claude Code" "$DRY_RUN"
  INSTALLED_SKILL_DIRS+=("$CLAUDE_SKILL_DIR")
fi

if [[ "$DRY_RUN" -eq 0 && "$SKIP_SMOKE_TEST" -eq 0 ]]; then
  assert_install_result "$REPO_ROOT" "${INSTALLED_SKILL_DIRS[@]}"
fi

TOOLKIT_COMMAND="$REPO_ROOT/silmaril-mac.sh"

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf '\nDry run complete.\n'
else
  chmod +x "$TOOLKIT_COMMAND"
  printf '\nInstalled silmaril-cdp skill successfully.\n'
fi

printf 'Toolkit root: %s\n' "$REPO_ROOT"
printf 'Toolkit command: %s\n' "$TOOLKIT_COMMAND"
for skill_dir in "${INSTALLED_SKILL_DIRS[@]}"; do
  printf 'Skill path: %s\n' "$skill_dir"
done

if ! command -v pwsh >/dev/null 2>&1; then
  printf '\nNote: pwsh is not installed on PATH. Install PowerShell 7 before running Silmaril on macOS.\n'
fi

printf '\nSmoke test commands:\n'
printf "  bash '%s' openbrowser --json\n" "$TOOLKIT_COMMAND"
printf "  bash '%s' openUrl 'https://example.com' --json\n" "$TOOLKIT_COMMAND"
printf "  bash '%s' get-text 'body' --json\n" "$TOOLKIT_COMMAND"
