[CmdletBinding()]
param(
  [ValidateSet("codex", "claude", "both")]
  [string]$Target = "both",
  [string]$ToolkitDir,
  [string]$CodexSkillsDir,
  [string]$ClaudeSkillsDir,
  [string]$RepoUrl = "https://github.com/Malac12/silmaril-CDP-tools.git",
  [string]$ArchiveUrl = "https://github.com/Malac12/silmaril-CDP-tools/archive/refs/heads/main.zip",
  [switch]$Force,
  [switch]$SkipSmokeTest,
  [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-InstallerStep {
  param(
    [string]$Message
  )

  Write-Host ("==> " + $Message)
}

function Test-SilmarilRepoRoot {
  param(
    [string]$Path
  )

  if ([string]::IsNullOrWhiteSpace($Path)) {
    return $false
  }

  $skillPath = Join-Path -Path $Path -ChildPath "skills\silmaril-cdp\SKILL.md"
  $commandPath = Join-Path -Path $Path -ChildPath "silmaril.cmd"
  return (Test-Path -LiteralPath $skillPath) -and (Test-Path -LiteralPath $commandPath)
}

function Get-DefaultToolkitDir {
  if (-not [string]::IsNullOrWhiteSpace($env:USERPROFILE)) {
    return (Join-Path -Path $env:USERPROFILE -ChildPath "silmaril-cdp-tools")
  }

  return (Join-Path -Path $HOME -ChildPath "silmaril-cdp-tools")
}

function Install-SilmarilToolkitArchive {
  param(
    [string]$DestinationDir,
    [string]$DownloadUrl
  )

  $tempRoot = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath ("silmaril-install-" + [guid]::NewGuid().ToString("N"))
  $zipPath = Join-Path -Path $tempRoot -ChildPath "toolkit.zip"
  $extractRoot = Join-Path -Path $tempRoot -ChildPath "extract"

  New-Item -Path $tempRoot -ItemType Directory -Force | Out-Null
  New-Item -Path $extractRoot -ItemType Directory -Force | Out-Null

  try {
    Invoke-WebRequest -Uri $DownloadUrl -OutFile $zipPath
    Expand-Archive -LiteralPath $zipPath -DestinationPath $extractRoot -Force

    $expandedRepo = Get-ChildItem -Path $extractRoot -Directory | Select-Object -First 1
    if ($null -eq $expandedRepo) {
      throw "Downloaded archive did not contain a repository root directory."
    }

    Move-Item -LiteralPath $expandedRepo.FullName -Destination $DestinationDir
  }
  finally {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
  }
}

function Resolve-SilmarilRepoRoot {
  param(
    [string]$RequestedToolkitDir,
    [bool]$ReplaceExisting,
    [bool]$SimulationMode,
    [string]$DownloadRepoUrl,
    [string]$DownloadArchiveUrl
  )

  if (Test-SilmarilRepoRoot -Path $PSScriptRoot) {
    return (Resolve-Path -LiteralPath $PSScriptRoot).Path
  }

  $destinationDir = $RequestedToolkitDir
  if ([string]::IsNullOrWhiteSpace($destinationDir)) {
    $destinationDir = Get-DefaultToolkitDir
  }

  if (Test-SilmarilRepoRoot -Path $destinationDir) {
    return (Resolve-Path -LiteralPath $destinationDir).Path
  }

  if (Test-Path -LiteralPath $destinationDir) {
    if (-not $ReplaceExisting) {
      throw "Existing path is not a Silmaril toolkit checkout: $destinationDir. Re-run with -Force to replace it."
    }

    if ($SimulationMode) {
      Write-InstallerStep "Would remove existing path: $destinationDir"
    }
    else {
      Remove-Item -LiteralPath $destinationDir -Recurse -Force
    }
  }

  if ($SimulationMode) {
    Write-InstallerStep "Would install toolkit repo to $destinationDir"
    return $destinationDir
  }

  $parentDir = Split-Path -Parent $destinationDir
  if (-not [string]::IsNullOrWhiteSpace($parentDir)) {
    New-Item -Path $parentDir -ItemType Directory -Force | Out-Null
  }

  $gitCommand = Get-Command git -ErrorAction SilentlyContinue
  if ($null -ne $gitCommand) {
    Write-InstallerStep "Cloning toolkit with git into $destinationDir"
    & git clone $DownloadRepoUrl $destinationDir
    if ($LASTEXITCODE -ne 0) {
      throw "git clone failed."
    }
  }
  else {
    Write-InstallerStep "git not found. Downloading toolkit archive into $destinationDir"
    Install-SilmarilToolkitArchive -DestinationDir $destinationDir -DownloadUrl $DownloadArchiveUrl
  }

  if (-not (Test-SilmarilRepoRoot -Path $destinationDir)) {
    throw "Installed toolkit checkout is missing required files: $destinationDir"
  }

  return (Resolve-Path -LiteralPath $destinationDir).Path
}

function Write-SilmarilLocalPathsFile {
  param(
    [string]$SkillDir,
    [string]$ToolkitRoot
  )

  $toolkitCommand = Join-Path -Path $ToolkitRoot -ChildPath "silmaril.cmd"
  $localPathsPath = Join-Path -Path $SkillDir -ChildPath "LOCAL_PATHS.md"
  $content = @(
    "# Local Paths"
    ""
    "This file was generated by `install-skill.ps1`."
    ""
    ("- Toolkit root: " + $ToolkitRoot)
    ("- Toolkit command: " + $toolkitCommand)
    ("- Repository URL: " + $RepoUrl)
  ) -join [Environment]::NewLine

  Set-Content -LiteralPath $localPathsPath -Value $content -Encoding UTF8
}

function Install-SilmarilSkill {
  param(
    [string]$SourceSkillDir,
    [string]$DestinationSkillDir,
    [string]$ToolkitRoot,
    [string]$TargetName,
    [bool]$SimulationMode
  )

  $destinationParent = Split-Path -Parent $DestinationSkillDir

  if ($SimulationMode) {
    Write-InstallerStep "Would install $TargetName skill to $DestinationSkillDir"
    return
  }

  New-Item -Path $destinationParent -ItemType Directory -Force | Out-Null
  if (Test-Path -LiteralPath $DestinationSkillDir) {
    Remove-Item -LiteralPath $DestinationSkillDir -Recurse -Force
  }

  Copy-Item -LiteralPath $SourceSkillDir -Destination $DestinationSkillDir -Recurse -Force
  Write-SilmarilLocalPathsFile -SkillDir $DestinationSkillDir -ToolkitRoot $ToolkitRoot
}

function Assert-SilmarilInstallResult {
  param(
    [string[]]$SkillDirs,
    [string]$ToolkitRoot
  )

  $toolkitCommand = Join-Path -Path $ToolkitRoot -ChildPath "silmaril.cmd"
  if (-not (Test-Path -LiteralPath $toolkitCommand)) {
    throw "Toolkit command not found after install: $toolkitCommand"
  }

  foreach ($skillDir in $SkillDirs) {
    $skillDoc = Join-Path -Path $skillDir -ChildPath "SKILL.md"
    $localPaths = Join-Path -Path $skillDir -ChildPath "LOCAL_PATHS.md"
    if (-not (Test-Path -LiteralPath $skillDoc)) {
      throw "Installed skill is missing SKILL.md: $skillDir"
    }
    if (-not (Test-Path -LiteralPath $localPaths)) {
      throw "Installed skill is missing LOCAL_PATHS.md: $skillDir"
    }
  }
}

$resolvedToolkitDir = $ToolkitDir
if ([string]::IsNullOrWhiteSpace($resolvedToolkitDir)) {
  $resolvedToolkitDir = Get-DefaultToolkitDir
}

if ([string]::IsNullOrWhiteSpace($CodexSkillsDir)) {
  $CodexSkillsDir = Join-Path -Path $HOME -ChildPath ".codex\skills"
}
if ([string]::IsNullOrWhiteSpace($ClaudeSkillsDir)) {
  $ClaudeSkillsDir = Join-Path -Path $HOME -ChildPath ".claude\skills"
}

$repoRoot = Resolve-SilmarilRepoRoot -RequestedToolkitDir $resolvedToolkitDir -ReplaceExisting $Force.IsPresent -SimulationMode $DryRun.IsPresent -DownloadRepoUrl $RepoUrl -DownloadArchiveUrl $ArchiveUrl
$sourceSkillDir = Join-Path -Path $repoRoot -ChildPath "skills\silmaril-cdp"
if (-not $DryRun -and -not (Test-Path -LiteralPath $sourceSkillDir)) {
  throw "Skill source directory not found: $sourceSkillDir"
}

$installedSkillDirs = New-Object System.Collections.Generic.List[string]

if ($Target -eq "codex" -or $Target -eq "both") {
  $codexSkillDir = Join-Path -Path $CodexSkillsDir -ChildPath "silmaril-cdp"
  Install-SilmarilSkill -SourceSkillDir $sourceSkillDir -DestinationSkillDir $codexSkillDir -ToolkitRoot $repoRoot -TargetName "Codex" -SimulationMode $DryRun.IsPresent
  [void]$installedSkillDirs.Add($codexSkillDir)
}

if ($Target -eq "claude" -or $Target -eq "both") {
  $claudeSkillDir = Join-Path -Path $ClaudeSkillsDir -ChildPath "silmaril-cdp"
  Install-SilmarilSkill -SourceSkillDir $sourceSkillDir -DestinationSkillDir $claudeSkillDir -ToolkitRoot $repoRoot -TargetName "Claude Code" -SimulationMode $DryRun.IsPresent
  [void]$installedSkillDirs.Add($claudeSkillDir)
}

if (-not $DryRun -and -not $SkipSmokeTest) {
  Assert-SilmarilInstallResult -SkillDirs $installedSkillDirs.ToArray() -ToolkitRoot $repoRoot
}

$toolkitCommand = Join-Path -Path $repoRoot -ChildPath "silmaril.cmd"
if ($DryRun) {
  Write-Host ""
  Write-Host "Dry run complete."
}
else {
  Write-Host ""
  Write-Host "Installed silmaril-cdp skill successfully."
}

Write-Host ("Toolkit root: " + $repoRoot)
Write-Host ("Toolkit command: " + $toolkitCommand)
foreach ($skillDir in $installedSkillDirs) {
  Write-Host ("Skill path: " + $skillDir)
}

Write-Host ""
Write-Host "Smoke test commands:"
Write-Host ("  & '" + $toolkitCommand + "' openbrowser --json")
Write-Host ("  & '" + $toolkitCommand + "' openUrl 'https://example.com' --json")
Write-Host ("  & '" + $toolkitCommand + "' get-text 'body' --json")
